### ISSUE TITLE
verifiable-credentials package compatibility issue with React Native

### ISSUE THREAD

**Issue by pkhien95** [verida/verida-js#140]
After installing @verida/verifiable-credentials in React Native, the app is showing this error:

```
Error: While trying to resolve module `did-jwt` from file `/Users/hienphung/repos/react/vault-mobile/node_modules/did-jwt-vc/lib/index.js`, the package `/Users/hienphung/repos/react/vault-mobile/node_modules/did-jwt-vc/node_modules/did-jwt/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/hienphung/repos/react/vault-mobile/node_modules/did-jwt-vc/node_modules/did-jwt/lib/index.cjs`. Indeed, none of these files exist:

  * /Users/hienphung/repos/react/vault-mobile/node_modules/did-jwt-vc/node_modules/did-jwt/lib/index.cjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * /Users/hienphung/repos/react/vault-mobile/node_modules/did-jwt-vc/node_modules/did-jwt/lib/index.cjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
    at DependencyGraph.resolveDependency (/Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:376:17)
    at Object.resolve (/Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/hienphung/repos/react/vault-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
```

It looks like the dependency `did-jwt-vc` has issue in RN environment. Possible solutions are:
- Find a way to modify the dependencies to make it compatible with RN
- Create a fork of `@verida/verifiable-credentials` package that is for RN only (similar to client-ts -> client-rn)

**Comment by cmcWebCode40** [comment]
@tahpot, any thoughts on how this issue could be resolved?

**Comment by tahpot** [comment]
@pkhien95 That error indicates missing files. Can you confirm the dependency was actually built?

**Comment by nick-verida** [comment]
@pkhien95 Have you tried this? https://stackoverflow.com/a/60126739/280795

**Comment by pkhien95** [comment]
Closed as it can be fixed in the Vault instead.
