### ISSUE TITLE
Unable to create DID: Already exists

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#340]
When using `2.3.6` we see this error:

```
Error: Unable to create DID: Already exists
    at VdaDid.<anonymous> (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/vda-did/src/vdaDid.ts:82:23)
    at step (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/vda-did/dist/vdaDid.js:33:23)
    at Object.next (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/vda-did/dist/vdaDid.js:14:53)
    at fulfilled (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/vda-did/dist/vdaDid.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/src/did-context-manager.ts:142
        throw new Error(
              ^
Error: Unable to force creation of storage context for this DID
    at DIDContextManager.<anonymous> (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/src/did-context-manager.ts:142:15)
    at step (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/dist/did-context-manager.js:33:23)
    at Object.next (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/dist/did-context-manager.js:14:53)
    at fulfilled (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/dist/did-context-manager.js:5:58
```

However it works when using the linked local version.

**Comment by tahpot** [comment]
I believe there was an issue with the latest build that was deployed to npm. This problem doesn't occur in local builds from `main` branch, so I am assuming this will be fixed in the next release.

We can verify and close this issue then.
