### ISSUE TITLE
Unable to send message. Recipient does not have an inbox for that context (Verida: Vault)

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#341]
When doing 

```
await messaging.send("did:vda:testnet:0xf080913daa2f1F2F93dfF494a2F3E6e1A2e2C492", messageType, data, subject, config)
```

I get the following error:

```
Error: Unable to send message. Recipient does not have an inbox for that context (Verida: Vault)
    at VeridaOutbox.<anonymous> (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/src/context/engines/verida/messaging/outbox.ts:93:13)
    at step (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/dist/context/engines/verida/messaging/outbox.js:33:23)
    at Object.throw (/Users/nlothian/dev/verida/didmessaging/node_modules/@verida/client-ts/dist/context/engines/verida/messaging/outbox.js:14:53)
    at rejected (/Users/nlo
```

**Comment by tahpot** [comment]
I can not repeat. Works fine for me.

@nick-verida to close or provide more info
